### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by PrettyMeng** [shuding/site#4]
Hi there,

By running `yarn` and `yarn dev` I got the following error: 

event - build page: /
wait  - compiling...
error - ./pages/index.mdx
Could not parse import/exports with acorn: SyntaxError: Unexpected token

I'm build on WSL. Any idea about this error? Many thanks!

**Comment by ifyour** [comment]
Use yarn, because the author provides `yarn.lock` to lock the dependency version.

**Comment by PrettyMeng** [comment]
> Use yarn, because the author provides `yarn.lock` to lock the dependency version.

Thanks for your kind reply. However, I still get this error by running `yarn` and `yarn dev`.

**Comment by shuding** [comment]
Could you try removing `node_modules` and `.next`, and then install again? I upgraded all the dependences and it works fine for me.

**Comment by PrettyMeng** [comment]
> Could you try removing `node_modules` and `.next`, and then install again? I upgraded all the dependences and it works fine for me.

Thanks for your reply! By removing `node_modules` and `.next` and then run `yarn`; `yarn dev`, I still got this error. Not sure why this is the case.

**Comment by PrettyMeng** [comment]
> > Could you try removing `node_modules` and `.next`, and then install again? I upgraded all the dependences and it works fine for me.
> 
> Thanks for your reply! By removing `node_modules` and `.next` and then run `yarn`; `yarn dev`, I still got this error. Not sure why this is the case.

By updating yarn.lock and package.json, now it works for me. Thanks!
